<Project>
  <PropertyGroup>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <InformationalVersion>1.1.2</InformationalVersion>
    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts\build\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\obj\**;**\bin\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
