<Project>
  <PropertyGroup>
    <Version>0.7.2-beta</Version>
    <AssemblyVersion>0.7.2.0</AssemblyVersion>
    <FileVersion>0.7.2.0</FileVersion>
    <InformationalVersion>0.7.2-beta</InformationalVersion>
    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts\build\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\obj\**;**\bin\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
